import { ColType } from "@/types";

export const scheduleServices = [
  { label: "3 Min Walk Test (PT)", value: "walk-test" },
  // { label: 'Berg Balance Test (PT)', value: 'Berg_Balance_Test_(PT)' },
  { label: "Consent (other)", value: "consent" },
  // { label: 'D/C Assess E (Oasis)', value: 'DischargeE' },
  // { label: 'Death at Home E (Oasis)', value: 'DeathE' },
  { label: "HHA Visit (HHA)", value: "hha-visit" },
  // { label: 'Infusion Nursing Visit (SN)', value: 'Infusion_Nursing_Visit_(SN)' },
  // { label: 'M.A.R (Ped)', value: 'M.A.R_(Ped)' },
  // { label: 'Medicaid HHA Care Plan (HHA)', value: 'Med.HHA.CarePlan_(HHA)' },
  // { label: 'Medicaid HHA Progress Notes (HHA)', value: 'Med.HHA.Progress_(HHA)' },
  { label: "Nursing Assessment (Other)", value: "nursing" },
  { label: "Oasis Followup E (Oasis)", value: "oasis-followup" },
  // { label: 'OT Discharge (PT)', value: 'OT_D_C_(PT)' },
  { label: "OT Eval (PT)", value: "ot-eval" },
  // { label: 'OT Re-Eval (PT)', value: 'OT_Re-Eval_(PT)' },
  { label: "OT/OTA Visit (PT)", value: "ot-visit" },
  // { label: 'PAS Care (PrivatePay)', value: 'PAS_Care_(PrivatePay)' },
  // { label: 'POC Upload (SN)', value: 'POC_Upload_(SN)' },
  // { label: 'Post Hosp Re-Eval (PT)', value: 'Post_Hosp_Re-Eval_(PT)' },
  // { label: 'PT 30th Day Re-eval (PT)', value: 'PT_30th_Re-Eval_(PT)' },
  // { label: 'PT Discharge (PT)', value: 'PT_D_C_(PT)' },
  { label: "PT Eval (PT)", value: "pt-eval" },
  // { label: 'PT Re-Eval (PT)', value: 'PT_Re-Eval_(PT)' },
  { label: "PT/PTA Visit (PT)", value: "pt-visit" },
  // { label: 'Re-Eval (PT)', value: 'Re-Eval_(PT)' },
  // { label: 'Recert Assess E (Oasis)', value: 'RecertE' },
  // { label: 'Recert Assess E (PT) (PT)', value: 'RecertE_PT' },
  // { label: 'Respite (SN)', value: 'Respite' },
  // { label: 'Respite Care (PrivatePay)', value: 'Respite_Care_(PrivatePay)' },
  // { label: 'ROC Assess E (Oasis)', value: 'ROCE' },
  // { label: 'ROC Assess E (PT) (PT)', value: 'ROCE_PT' },
  // { label: 'SN PRN Visit (SN)', value: 'SN_PRN' },
  { label: "SN Visit (SN)", value: "sn-note" },
  // { label: 'SN Visit (AM) (SN)', value: 'SN_Visit_(AM)_(SN)' },
  // { label: 'SN Visit (PM) (SN)', value: 'SN_Visit_(PM)_(SN)' },
  { label: "SOC Assess E (Oasis)", value: "soc-assess" },
  // { label: 'SOC Assess E (PT) (PT)', value: 'SOCE_PT' },
  // { label: 'ST Discharge (PT)', value: 'ST_D_C_(PT)' },
  { label: "ST Eval (PT)", value: "st-eval" },
  // { label: 'ST Re-Eval (PT)', value: 'ST_Re-Eval_(PT)' },
  { label: "ST/STA Visit (PT)", value: "st-visit" },
  // { label: 'Sup. Visit (SN)', value: 'SN_Sup' },
  // { label: 'Timed Up & Go (PT)', value: 'TUG' },
  // { label: 'Tinetti (PT)', value: 'Tinetti' },
  // { label: 'Transfer Discharge E (Oasis)', value: 'XferDischargeE' },
  // { label: 'Transfer Not Discharge E (Oasis)', value: 'XferNotDischargeE' },
];

export const scheduleColumns: ColType[] = [
  {
    key: "scheduleDate",
    label: "Schedule Date",
    visible: true,
  },
  {
    key: "caregivers",
    label: "Care-Givers",
    visible: true,
  },
  {
    key: "services",
    label: "Services",
    visible: true,
  },
  {
    key: "timeIn",
    label: "Time-In",
    visible: true,
  },
  {
    key: "timeOut",
    label: "Time-Out",
    visible: true,
  },
  {
    key: "comments",
    label: "Comments",
    visible: true,
  },
  {
    key: "delete",
    label: "Delete",
    visible: true,
  },
];
