import { z } from "zod";

import { InferSchema } from "@/types";

export const careCoordinationSchema = z.object({
  treatmentProvided: z.string().optional(),
  criteriaOneA: z.string().optional(),
  criteriaOneB: z.string().optional(),
  criteriaTwoA: z.string().optional(),
  criteriaTwoB: z.string().optional(),
  medicalCare: z.string().optional(),
  hospitalRiskAssessment: z.string().optional(),
  coordinationOfCare: z.array(z.string()).optional(),
  otherCoordinationOfCare: z.string().optional(),
  coordinationOfCareRegard: z.string().optional(),
  discussion: z.string().optional(),
  isLastPhysician: z.boolean().optional(),
  lastPhysicianVisit: z.date().optional(),
  careMeasure: z.array(z.string()).optional(),
  emergencyRoomVisit: z.date().optional(),
  influenzaVaccine: z.date().optional(),
  influenzaVaccineGivenBy: z.string().optional(),
  pneumococcalVaccine: z.date().optional(),
  pneumococcalVaccineGivenBy: z.string().optional(),
  isDischargeNotice: z.boolean().optional(),
  dischargePlanSupervisor: z.string().optional(),
  staSupervision: z.array(z.string()).optional(),
  employee: z.string().optional(),
  employeeTitle: z.array(z.string()).optional(),
  continueFrequency: z.string().optional(),
  objectEvaluation: z.string().optional(),
  progressToGoal: z.string().optional(),
  comments: z.string().optional(),
});

export type CareCoordinationForm = InferSchema<typeof careCoordinationSchema>;

export const careCoordinationDefaultValue: CareCoordinationForm = {
  treatmentProvided: "",
  criteriaOneA: "",
  criteriaOneB: "",
  criteriaTwoA: "",
  criteriaTwoB: "",
  medicalCare: "",
  hospitalRiskAssessment: "",
  coordinationOfCare: [],
  otherCoordinationOfCare: "",
  coordinationOfCareRegard: "",
  discussion: "",
  isLastPhysician: false,
  lastPhysicianVisit: undefined,
  careMeasure: [],
  emergencyRoomVisit: undefined,
  influenzaVaccine: undefined,
  influenzaVaccineGivenBy: "",
  pneumococcalVaccine: undefined,
  pneumococcalVaccineGivenBy: "",
  isDischargeNotice: false,
  dischargePlanSupervisor: "",
  staSupervision: [],
  employee: "",
  employeeTitle: [],
  continueFrequency: "",
  objectEvaluation: "",
  progressToGoal: "",
  comments: "",
};
