import { z } from "zod";

import { ProviderSchema } from "@/prisma/zod-schema";
import { InferSchema } from "@/types";

export const providerFormSchema = [
  z.object({
    providerName: z.string().optional().nullable(),
    dmetpi: z.string().optional().nullable(),
    billingName: z.string().optional().nullable(),
    identifierName: z.string().optional().nullable(),
    providerNumber: z.string().optional().nullable(),
    benefitCode: z.string().optional().nullable(),
    contact1: z.string().optional().nullable(),
    npi: z.string().optional().nullable(),
    contact2: z.string().optional().nullable(),
    taxId: z.string().optional().nullable(),
    address1: z.string().optional().nullable(),
    stateAssignedId: z.string().optional().nullable(),
    address2: z.string().optional().nullable(),
    branchId: z.string().optional().nullable(),
    state: z.string().optional().nullable(),
    phone: z.string().optional().nullable(),
    city: z.string().optional().nullable(),
    cellPhone: z.string().optional().nullable(),
    zipCode: z.string().optional().nullable(),
    fax: z.string().optional().nullable(),
    tpi: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
    pressGaneyClientId: z.string().optional().nullable(),
    startDay: z.string().optional().nullable().nullable(),
    taxonomy: z.string().optional().nullable(),
    taxonomyCode: z.string().optional().nullable(),
    licenseNumber: z.string().optional().nullable(),
    novaetusId: z.string().optional().nullable(),
    providerType: z.string().optional().nullable().nullable(),
  }),
  z.object({
    qioAddress1: z.string().optional().nullable(),
    qioAddress2: z.string().optional().nullable(),
    qioCity: z.string().optional().nullable(),
    qioState: z.string().optional().nullable(),
    qioZipCode: z.string().optional().nullable(),
    qioPhone: z.string().optional().nullable(),
    qioFax: z.string().optional().nullable(),
    qioLocalPhone: z.string().optional().nullable(),
  }),
  z.object({
    ppiName: z.string().optional().nullable(),
    ppiNpi: z.string().optional().nullable(),
    ppiAddress1: z.string().optional().nullable(),
    ppiAddress2: z.string().optional().nullable(),
    ppiCity: z.string().optional().nullable(),
    ppiState: z.string().optional().nullable(),
    ppiZipCode: z.string().optional().nullable(),
    ppiTaxId: z.string().optional().nullable(),
    ppiTaxType: z.string().optional().nullable(),
    ppiProviderId: z.string().optional().nullable(),
    ppiProviderNumber: z.string().optional().nullable(),
    ppiSecId1: z.string().optional().nullable(),
    ppiSecType1: z.string().optional().nullable(),
    ppiSecId2: z.string().optional().nullable(),
    ppiSecType2: z.string().optional().nullable(),
  }),
];

export const providerSchema = ProviderSchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
  active: true,
});

export type ProviderForm = InferSchema<typeof providerSchema>;

export const providerDefaultValues: ProviderForm = {
  providerName: "",
  dmetpi: "",
  billingName: "",
  identifierName: "",
  providerNumber: "",
  benefitCode: "",
  contact1: "",
  npi: "",
  contact2: "",
  taxId: "",
  address1: "",
  stateAssignedId: "",
  address2: "",
  branchId: "",
  state: "",
  phone: "",
  city: "",
  cellPhone: "",
  zipCode: "",
  fax: "",
  tpi: "",
  email: "",
  pressGaneyClientId: "",
  startDay: null,
  taxonomy: "",
  taxonomyCode: "",
  licenseNumber: "",
  novaetusId: "",
  providerType: null,
  qioAddress1: "",
  qioAddress2: "",
  qioCity: "",
  qioState: "",
  qioZipCode: "",
  qioPhone: "",
  qioFax: "",
  qioLocalPhone: "",
  ppiName: "",
  ppiNpi: "",
  ppiAddress1: "",
  ppiAddress2: "",
  ppiCity: "",
  ppiState: "",
  ppiZipCode: "",
  ppiTaxId: "",
  ppiTaxType: "",
  ppiProviderId: "",
  ppiProviderNumber: "",
  ppiSecId1: "",
  ppiSecType1: "",
  ppiSecId2: "",
  ppiSecType2: "",
};
