import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function seedAssessmentTemplates() {
  console.log("Seeding assessment templates...");

  // PT Evaluation Template
  const ptTemplate = await prisma.assessmentTemplate.create({
    data: {
      name: "Physical Therapy Evaluation",
      description: "Initial PT evaluation for home health patients (v1 - Simplified)",
      version: 1,
      isActive: true,
      isRequired: false,
      displayOrder: 1,
      scoringMethod: "CUSTOM",
      sections: {
        create: [
          {
            sectionType: "PT_HISTORY",
            title: "Patient History",
            description: "Medical history and prior level of function",
            displayOrder: 1,
            items: {
              create: [
                {
                  code: "PT_DIAGNOSIS",
                  question: "Primary PT Diagnosis",
                  responseType: "TEXT",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "PT_PRIOR_LEVEL",
                  question: "Prior Level of Function",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "independent", label: "Independent - No assistance needed" },
                    { value: "modified_independent", label: "Modified Independent - Uses devices" },
                    { value: "supervision", label: "Supervision - Standby assistance" },
                    { value: "minimal_assist", label: "Minimal Assistance - 25% help" },
                    { value: "moderate_assist", label: "Moderate Assistance - 50% help" },
                    { value: "maximal_assist", label: "Maximal Assistance - 75% help" },
                    { value: "dependent", label: "Dependent - Total assistance" },
                  ],
                },
                {
                  code: "PT_ONSET_DATE",
                  question: "Date of Onset/Surgery",
                  responseType: "DATE",
                  displayOrder: 3,
                  isRequired: false,
                },
                {
                  code: "PT_PRECAUTIONS",
                  question: "Precautions/Contraindications",
                  responseType: "TEXT",
                  displayOrder: 4,
                  isRequired: false,
                },
              ],
            },
          },
          {
            sectionType: "PAIN",
            title: "Pain Assessment",
            description: "Current pain status",
            displayOrder: 2,
            items: {
              create: [
                {
                  code: "PT_PAIN_PRESENT",
                  question: "Is pain present?",
                  responseType: "YES_NO",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "PT_PAIN_LEVEL",
                  question: "Pain Level (0-10)",
                  responseType: "SCALE",
                  displayOrder: 2,
                  isRequired: false,
                  minValue: 0,
                  maxValue: 10,
                  showIf: { itemCode: "PT_PAIN_PRESENT", value: true },
                },
                {
                  code: "PT_PAIN_LOCATION",
                  question: "Pain Location(s)",
                  responseType: "TEXT",
                  displayOrder: 3,
                  isRequired: false,
                  showIf: { itemCode: "PT_PAIN_PRESENT", value: true },
                },
                {
                  code: "PT_PAIN_DESCRIPTION",
                  question: "Pain Description",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 4,
                  isRequired: false,
                  responseOptions: [
                    { value: "sharp", label: "Sharp" },
                    { value: "dull", label: "Dull" },
                    { value: "aching", label: "Aching" },
                    { value: "burning", label: "Burning" },
                    { value: "throbbing", label: "Throbbing" },
                    { value: "stabbing", label: "Stabbing" },
                  ],
                  showIf: { itemCode: "PT_PAIN_PRESENT", value: true },
                },
              ],
            },
          },
          {
            sectionType: "PT_MOBILITY",
            title: "Mobility Assessment",
            description: "Current mobility status and gait assessment",
            displayOrder: 3,
            items: {
              create: [
                {
                  code: "PT_BED_MOBILITY",
                  question: "Bed Mobility",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "7", label: "Independent" },
                    { value: "6", label: "Modified Independent" },
                    { value: "5", label: "Supervision" },
                    { value: "4", label: "Minimal Assistance" },
                    { value: "3", label: "Moderate Assistance" },
                    { value: "2", label: "Maximal Assistance" },
                    { value: "1", label: "Dependent" },
                  ],
                  scoreMapping: { "7": 7, "6": 6, "5": 5, "4": 4, "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "PT_TRANSFERS",
                  question: "Transfers (Bed/Chair)",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "7", label: "Independent" },
                    { value: "6", label: "Modified Independent" },
                    { value: "5", label: "Supervision" },
                    { value: "4", label: "Minimal Assistance" },
                    { value: "3", label: "Moderate Assistance" },
                    { value: "2", label: "Maximal Assistance" },
                    { value: "1", label: "Dependent" },
                  ],
                  scoreMapping: { "7": 7, "6": 6, "5": 5, "4": 4, "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "PT_AMBULATION",
                  question: "Ambulation",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "7", label: "Independent" },
                    { value: "6", label: "Modified Independent (with device)" },
                    { value: "5", label: "Supervision" },
                    { value: "4", label: "Minimal Assistance" },
                    { value: "3", label: "Moderate Assistance" },
                    { value: "2", label: "Maximal Assistance" },
                    { value: "1", label: "Non-ambulatory" },
                  ],
                  scoreMapping: { "7": 7, "6": 6, "5": 5, "4": 4, "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "PT_ASSISTIVE_DEVICE",
                  question: "Assistive Device Used",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 4,
                  isRequired: false,
                  responseOptions: [
                    { value: "none", label: "None" },
                    { value: "cane", label: "Cane" },
                    { value: "quad_cane", label: "Quad Cane" },
                    { value: "walker", label: "Walker" },
                    { value: "rollator", label: "Rollator" },
                    { value: "wheelchair", label: "Wheelchair" },
                    { value: "crutches", label: "Crutches" },
                  ],
                },
                {
                  code: "PT_GAIT_PATTERN",
                  question: "Gait Pattern",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 5,
                  isRequired: false,
                  responseOptions: [
                    { value: "normal", label: "Normal" },
                    { value: "antalgic", label: "Antalgic (pain-avoidant)" },
                    { value: "ataxic", label: "Ataxic (uncoordinated)" },
                    { value: "shuffling", label: "Shuffling" },
                    { value: "steppage", label: "Steppage (foot drop)" },
                    { value: "waddling", label: "Waddling" },
                  ],
                },
              ],
            },
          },
          {
            sectionType: "PT_BALANCE",
            title: "Balance Assessment",
            description: "Balance and fall risk screening",
            displayOrder: 4,
            items: {
              create: [
                {
                  code: "PT_SITTING_BALANCE",
                  question: "Sitting Balance",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "normal", label: "Normal - Maintains independently" },
                    { value: "good", label: "Good - Maintains with minimal sway" },
                    { value: "fair", label: "Fair - Maintains with support nearby" },
                    { value: "poor", label: "Poor - Requires support to maintain" },
                  ],
                },
                {
                  code: "PT_STANDING_BALANCE",
                  question: "Standing Balance",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "normal", label: "Normal - Maintains independently" },
                    { value: "good", label: "Good - Maintains with minimal sway" },
                    { value: "fair", label: "Fair - Maintains with support nearby" },
                    { value: "poor", label: "Poor - Requires support to maintain" },
                  ],
                },
                {
                  code: "PT_TUG_TIME",
                  question: "Timed Up and Go (TUG) - seconds",
                  description: "Time to rise from chair, walk 3m, turn, return, sit",
                  responseType: "NUMBER",
                  displayOrder: 3,
                  isRequired: false,
                },
                {
                  code: "PT_FALL_HISTORY",
                  question: "History of falls in past 6 months?",
                  responseType: "YES_NO",
                  displayOrder: 4,
                  isRequired: true,
                },
                {
                  code: "PT_FALL_COUNT",
                  question: "Number of falls",
                  responseType: "NUMBER",
                  displayOrder: 5,
                  isRequired: false,
                  showIf: { itemCode: "PT_FALL_HISTORY", value: true },
                },
              ],
            },
          },
          {
            sectionType: "PT_TREATMENT_PLAN",
            title: "Treatment Plan",
            description: "Goals and planned interventions",
            displayOrder: 5,
            items: {
              create: [
                {
                  code: "PT_SHORT_TERM_GOALS",
                  question: "Short-Term Goals (2-4 weeks)",
                  responseType: "TEXT",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "PT_LONG_TERM_GOALS",
                  question: "Long-Term Goals (Discharge)",
                  responseType: "TEXT",
                  displayOrder: 2,
                  isRequired: true,
                },
                {
                  code: "PT_INTERVENTIONS",
                  question: "Planned Interventions",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "therapeutic_exercise", label: "Therapeutic Exercise" },
                    { value: "gait_training", label: "Gait Training" },
                    { value: "balance_training", label: "Balance Training" },
                    { value: "transfer_training", label: "Transfer Training" },
                    { value: "rom_exercises", label: "ROM Exercises" },
                    { value: "strengthening", label: "Strengthening" },
                    { value: "pain_management", label: "Pain Management" },
                    { value: "patient_education", label: "Patient/Caregiver Education" },
                    { value: "home_safety", label: "Home Safety Assessment" },
                  ],
                },
                {
                  code: "PT_FREQUENCY",
                  question: "Recommended Frequency",
                  responseType: "TEXT",
                  displayOrder: 4,
                  isRequired: true,
                  description: "e.g., 2x/week for 4 weeks",
                },
                {
                  code: "PT_REHAB_POTENTIAL",
                  question: "Rehabilitation Potential",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 5,
                  isRequired: true,
                  responseOptions: [
                    { value: "excellent", label: "Excellent" },
                    { value: "good", label: "Good" },
                    { value: "fair", label: "Fair" },
                    { value: "guarded", label: "Guarded" },
                    { value: "poor", label: "Poor" },
                  ],
                },
              ],
            },
          },
        ],
      },
    },
  });
  console.log(`Created PT Evaluation template: ${ptTemplate.id}`);

  // OT Evaluation Template
  const otTemplate = await prisma.assessmentTemplate.create({
    data: {
      name: "Occupational Therapy Evaluation",
      description: "Initial OT evaluation for home health patients (v1 - Simplified)",
      version: 1,
      isActive: true,
      isRequired: false,
      displayOrder: 2,
      scoringMethod: "CUSTOM",
      sections: {
        create: [
          {
            sectionType: "OT_HISTORY",
            title: "Patient History",
            description: "Medical history and living situation",
            displayOrder: 1,
            items: {
              create: [
                {
                  code: "OT_DIAGNOSIS",
                  question: "Primary OT Diagnosis",
                  responseType: "TEXT",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "OT_LIVING_SITUATION",
                  question: "Living Situation",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "alone", label: "Lives Alone" },
                    { value: "with_spouse", label: "Lives with Spouse/Partner" },
                    { value: "with_family", label: "Lives with Family" },
                    { value: "with_caregiver", label: "Lives with Caregiver" },
                    { value: "assisted_living", label: "Assisted Living" },
                  ],
                },
                {
                  code: "OT_PRIOR_LEVEL",
                  question: "Prior Level of ADL Function",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "independent", label: "Independent in all ADLs" },
                    { value: "modified_independent", label: "Modified Independent (uses devices)" },
                    { value: "minimal_assist", label: "Needed minimal assistance" },
                    { value: "moderate_assist", label: "Needed moderate assistance" },
                    { value: "dependent", label: "Dependent in ADLs" },
                  ],
                },
                {
                  code: "OT_HAND_DOMINANCE",
                  question: "Hand Dominance",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 4,
                  isRequired: true,
                  responseOptions: [
                    { value: "right", label: "Right" },
                    { value: "left", label: "Left" },
                    { value: "ambidextrous", label: "Ambidextrous" },
                  ],
                },
              ],
            },
          },
          {
            sectionType: "OT_ADL_STATUS",
            title: "ADL Assessment",
            description: "Activities of Daily Living status",
            displayOrder: 2,
            scoringMethod: "SUM",
            items: {
              create: [
                {
                  code: "OT_BATHING",
                  question: "Bathing/Showering",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "7", label: "Independent" },
                    { value: "6", label: "Modified Independent" },
                    { value: "5", label: "Supervision" },
                    { value: "4", label: "Minimal Assistance" },
                    { value: "3", label: "Moderate Assistance" },
                    { value: "2", label: "Maximal Assistance" },
                    { value: "1", label: "Dependent" },
                  ],
                  scoreMapping: { "7": 7, "6": 6, "5": 5, "4": 4, "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "OT_DRESSING_UPPER",
                  question: "Dressing - Upper Body",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "7", label: "Independent" },
                    { value: "6", label: "Modified Independent" },
                    { value: "5", label: "Supervision" },
                    { value: "4", label: "Minimal Assistance" },
                    { value: "3", label: "Moderate Assistance" },
                    { value: "2", label: "Maximal Assistance" },
                    { value: "1", label: "Dependent" },
                  ],
                  scoreMapping: { "7": 7, "6": 6, "5": 5, "4": 4, "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "OT_DRESSING_LOWER",
                  question: "Dressing - Lower Body",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "7", label: "Independent" },
                    { value: "6", label: "Modified Independent" },
                    { value: "5", label: "Supervision" },
                    { value: "4", label: "Minimal Assistance" },
                    { value: "3", label: "Moderate Assistance" },
                    { value: "2", label: "Maximal Assistance" },
                    { value: "1", label: "Dependent" },
                  ],
                  scoreMapping: { "7": 7, "6": 6, "5": 5, "4": 4, "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "OT_GROOMING",
                  question: "Grooming (hair, teeth, shaving)",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 4,
                  isRequired: true,
                  responseOptions: [
                    { value: "7", label: "Independent" },
                    { value: "6", label: "Modified Independent" },
                    { value: "5", label: "Supervision" },
                    { value: "4", label: "Minimal Assistance" },
                    { value: "3", label: "Moderate Assistance" },
                    { value: "2", label: "Maximal Assistance" },
                    { value: "1", label: "Dependent" },
                  ],
                  scoreMapping: { "7": 7, "6": 6, "5": 5, "4": 4, "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "OT_TOILETING",
                  question: "Toileting",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 5,
                  isRequired: true,
                  responseOptions: [
                    { value: "7", label: "Independent" },
                    { value: "6", label: "Modified Independent" },
                    { value: "5", label: "Supervision" },
                    { value: "4", label: "Minimal Assistance" },
                    { value: "3", label: "Moderate Assistance" },
                    { value: "2", label: "Maximal Assistance" },
                    { value: "1", label: "Dependent" },
                  ],
                  scoreMapping: { "7": 7, "6": 6, "5": 5, "4": 4, "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "OT_FEEDING",
                  question: "Feeding/Eating",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 6,
                  isRequired: true,
                  responseOptions: [
                    { value: "7", label: "Independent" },
                    { value: "6", label: "Modified Independent" },
                    { value: "5", label: "Supervision" },
                    { value: "4", label: "Minimal Assistance" },
                    { value: "3", label: "Moderate Assistance" },
                    { value: "2", label: "Maximal Assistance" },
                    { value: "1", label: "Dependent" },
                  ],
                  scoreMapping: { "7": 7, "6": 6, "5": 5, "4": 4, "3": 3, "2": 2, "1": 1 },
                },
              ],
            },
          },
          {
            sectionType: "OT_IADL_STATUS",
            title: "IADL Assessment",
            description: "Instrumental Activities of Daily Living",
            displayOrder: 3,
            scoringMethod: "SUM",
            items: {
              create: [
                {
                  code: "OT_MEAL_PREP",
                  question: "Meal Preparation",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "3", label: "Independent - Plans and prepares meals" },
                    { value: "2", label: "Needs assistance - With preparation" },
                    { value: "1", label: "Unable - Needs meals prepared" },
                  ],
                  scoreMapping: { "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "OT_HOUSEKEEPING",
                  question: "Light Housekeeping",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "3", label: "Independent - Maintains home" },
                    { value: "2", label: "Needs assistance - With some tasks" },
                    { value: "1", label: "Unable - Needs all tasks done" },
                  ],
                  scoreMapping: { "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "OT_LAUNDRY",
                  question: "Laundry",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "3", label: "Independent - Does own laundry" },
                    { value: "2", label: "Needs assistance - With some aspects" },
                    { value: "1", label: "Unable - Needs all laundry done" },
                  ],
                  scoreMapping: { "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "OT_MEDICATION_MGMT",
                  question: "Medication Management",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 4,
                  isRequired: true,
                  responseOptions: [
                    { value: "3", label: "Independent - Manages all medications" },
                    { value: "2", label: "Needs assistance - With setup/reminders" },
                    { value: "1", label: "Unable - Needs medications administered" },
                  ],
                  scoreMapping: { "3": 3, "2": 2, "1": 1 },
                },
                {
                  code: "OT_TELEPHONE",
                  question: "Telephone Use",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 5,
                  isRequired: true,
                  responseOptions: [
                    { value: "3", label: "Independent - Uses phone normally" },
                    { value: "2", label: "Needs assistance - Limited use" },
                    { value: "1", label: "Unable - Cannot use phone" },
                  ],
                  scoreMapping: { "3": 3, "2": 2, "1": 1 },
                },
              ],
            },
          },
          {
            sectionType: "OT_HOME_SAFETY",
            title: "Home Safety Assessment",
            description: "Environmental safety evaluation",
            displayOrder: 4,
            items: {
              create: [
                {
                  code: "OT_HOME_BARRIERS",
                  question: "Architectural Barriers Present",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "none", label: "None identified" },
                    { value: "stairs", label: "Stairs without railings" },
                    { value: "narrow_doorways", label: "Narrow doorways" },
                    { value: "uneven_floors", label: "Uneven floor surfaces" },
                    { value: "poor_lighting", label: "Poor lighting" },
                    { value: "throw_rugs", label: "Throw rugs/clutter" },
                    { value: "bathroom_safety", label: "Bathroom lacks safety equipment" },
                  ],
                },
                {
                  code: "OT_DME_NEEDED",
                  question: "DME Recommendations",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 2,
                  isRequired: false,
                  responseOptions: [
                    { value: "none", label: "None needed" },
                    { value: "grab_bars", label: "Grab bars" },
                    { value: "shower_chair", label: "Shower chair/bench" },
                    { value: "raised_toilet", label: "Raised toilet seat" },
                    { value: "reacher", label: "Reacher/grabber" },
                    { value: "long_handled", label: "Long-handled devices" },
                    { value: "sock_aid", label: "Sock aid" },
                    { value: "button_hook", label: "Button hook" },
                  ],
                },
                {
                  code: "OT_SAFETY_CONCERNS",
                  question: "Safety Concerns/Notes",
                  responseType: "TEXT",
                  displayOrder: 3,
                  isRequired: false,
                },
              ],
            },
          },
          {
            sectionType: "OT_TREATMENT_PLAN",
            title: "Treatment Plan",
            description: "Goals and planned interventions",
            displayOrder: 5,
            items: {
              create: [
                {
                  code: "OT_SHORT_TERM_GOALS",
                  question: "Short-Term Goals (2-4 weeks)",
                  responseType: "TEXT",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "OT_LONG_TERM_GOALS",
                  question: "Long-Term Goals (Discharge)",
                  responseType: "TEXT",
                  displayOrder: 2,
                  isRequired: true,
                },
                {
                  code: "OT_INTERVENTIONS",
                  question: "Planned Interventions",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "adl_training", label: "ADL Training" },
                    { value: "iadl_training", label: "IADL Training" },
                    { value: "fine_motor", label: "Fine Motor Training" },
                    { value: "upper_extremity", label: "Upper Extremity Strengthening" },
                    { value: "energy_conservation", label: "Energy Conservation" },
                    { value: "adaptive_equipment", label: "Adaptive Equipment Training" },
                    { value: "home_modification", label: "Home Modification Recommendations" },
                    { value: "caregiver_training", label: "Caregiver Training" },
                    { value: "cognitive_training", label: "Cognitive Training" },
                  ],
                },
                {
                  code: "OT_FREQUENCY",
                  question: "Recommended Frequency",
                  responseType: "TEXT",
                  displayOrder: 4,
                  isRequired: true,
                },
                {
                  code: "OT_REHAB_POTENTIAL",
                  question: "Rehabilitation Potential",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 5,
                  isRequired: true,
                  responseOptions: [
                    { value: "excellent", label: "Excellent" },
                    { value: "good", label: "Good" },
                    { value: "fair", label: "Fair" },
                    { value: "guarded", label: "Guarded" },
                    { value: "poor", label: "Poor" },
                  ],
                },
              ],
            },
          },
        ],
      },
    },
  });
  console.log(`Created OT Evaluation template: ${otTemplate.id}`);

  // ST Evaluation Template
  const stTemplate = await prisma.assessmentTemplate.create({
    data: {
      name: "Speech-Language Pathology Evaluation",
      description: "Initial ST evaluation for home health patients (v1 - Simplified)",
      version: 1,
      isActive: true,
      isRequired: false,
      displayOrder: 3,
      scoringMethod: "CUSTOM",
      sections: {
        create: [
          {
            sectionType: "ST_HISTORY",
            title: "Patient History",
            description: "Medical history and communication background",
            displayOrder: 1,
            items: {
              create: [
                {
                  code: "ST_DIAGNOSIS",
                  question: "Primary ST Diagnosis",
                  responseType: "TEXT",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "ST_ONSET",
                  question: "Onset of Communication/Swallowing Difficulty",
                  responseType: "DATE",
                  displayOrder: 2,
                  isRequired: false,
                },
                {
                  code: "ST_PRIOR_COMMUNICATION",
                  question: "Prior Communication Status",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "normal", label: "Normal communication" },
                    { value: "mild_difficulty", label: "Mild difficulty" },
                    { value: "moderate_difficulty", label: "Moderate difficulty" },
                    { value: "severe_difficulty", label: "Severe difficulty" },
                  ],
                },
                {
                  code: "ST_HEARING",
                  question: "Hearing Status",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 4,
                  isRequired: true,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mild_loss", label: "Mild hearing loss" },
                    { value: "moderate_loss", label: "Moderate hearing loss" },
                    { value: "severe_loss", label: "Severe hearing loss" },
                    { value: "hearing_aids", label: "Uses hearing aids" },
                  ],
                },
              ],
            },
          },
          {
            sectionType: "ST_COGNITION",
            title: "Cognition Assessment",
            description: "Cognitive-linguistic status",
            displayOrder: 2,
            items: {
              create: [
                {
                  code: "ST_ORIENTATION",
                  question: "Orientation",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "person", label: "Oriented to Person" },
                    { value: "place", label: "Oriented to Place" },
                    { value: "time", label: "Oriented to Time" },
                    { value: "situation", label: "Oriented to Situation" },
                  ],
                },
                {
                  code: "ST_ATTENTION",
                  question: "Attention/Concentration",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mildly_impaired", label: "Mildly Impaired" },
                    { value: "moderately_impaired", label: "Moderately Impaired" },
                    { value: "severely_impaired", label: "Severely Impaired" },
                  ],
                },
                {
                  code: "ST_MEMORY",
                  question: "Memory (Short-term)",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mildly_impaired", label: "Mildly Impaired" },
                    { value: "moderately_impaired", label: "Moderately Impaired" },
                    { value: "severely_impaired", label: "Severely Impaired" },
                  ],
                },
                {
                  code: "ST_PROBLEM_SOLVING",
                  question: "Problem Solving/Judgment",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 4,
                  isRequired: true,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mildly_impaired", label: "Mildly Impaired" },
                    { value: "moderately_impaired", label: "Moderately Impaired" },
                    { value: "severely_impaired", label: "Severely Impaired" },
                  ],
                },
              ],
            },
          },
          {
            sectionType: "ST_SPEECH",
            title: "Speech Assessment",
            description: "Speech production evaluation",
            displayOrder: 3,
            items: {
              create: [
                {
                  code: "ST_ARTICULATION",
                  question: "Articulation",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mildly_impaired", label: "Mildly Impaired" },
                    { value: "moderately_impaired", label: "Moderately Impaired" },
                    { value: "severely_impaired", label: "Severely Impaired" },
                  ],
                },
                {
                  code: "ST_VOICE",
                  question: "Voice Quality",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "hoarse", label: "Hoarse" },
                    { value: "breathy", label: "Breathy" },
                    { value: "strained", label: "Strained" },
                    { value: "weak", label: "Weak" },
                  ],
                },
                {
                  code: "ST_FLUENCY",
                  question: "Fluency",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mild_dysfluency", label: "Mild Dysfluency" },
                    { value: "moderate_dysfluency", label: "Moderate Dysfluency" },
                    { value: "severe_dysfluency", label: "Severe Dysfluency" },
                  ],
                },
                {
                  code: "ST_INTELLIGIBILITY",
                  question: "Speech Intelligibility",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 4,
                  isRequired: true,
                  responseOptions: [
                    { value: "100", label: "100% - Fully intelligible" },
                    { value: "75", label: "75% - Mostly intelligible" },
                    { value: "50", label: "50% - Sometimes intelligible" },
                    { value: "25", label: "25% - Rarely intelligible" },
                    { value: "0", label: "0% - Unintelligible" },
                  ],
                },
              ],
            },
          },
          {
            sectionType: "ST_SWALLOWING",
            title: "Swallowing Assessment",
            description: "Dysphagia screening",
            displayOrder: 4,
            items: {
              create: [
                {
                  code: "ST_SWALLOW_CONCERNS",
                  question: "Swallowing concerns present?",
                  responseType: "YES_NO",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "ST_DIET_TEXTURE",
                  question: "Current Diet Texture",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: false,
                  responseOptions: [
                    { value: "regular", label: "Regular" },
                    { value: "soft", label: "Soft/Easy to chew" },
                    { value: "mechanical_soft", label: "Mechanical Soft" },
                    { value: "puree", label: "Pureed" },
                    { value: "npo", label: "NPO (Nothing by mouth)" },
                  ],
                },
                {
                  code: "ST_LIQUID_CONSISTENCY",
                  question: "Liquid Consistency",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 3,
                  isRequired: false,
                  responseOptions: [
                    { value: "thin", label: "Thin liquids" },
                    { value: "nectar", label: "Nectar thick" },
                    { value: "honey", label: "Honey thick" },
                    { value: "pudding", label: "Pudding thick" },
                    { value: "npo", label: "NPO for liquids" },
                  ],
                },
                {
                  code: "ST_ASPIRATION_SIGNS",
                  question: "Signs of Aspiration Risk",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 4,
                  isRequired: false,
                  responseOptions: [
                    { value: "none", label: "None observed" },
                    { value: "coughing", label: "Coughing during/after meals" },
                    { value: "throat_clearing", label: "Frequent throat clearing" },
                    { value: "wet_voice", label: "Wet/gurgly voice after swallowing" },
                    { value: "food_pocketing", label: "Food pocketing" },
                    { value: "drooling", label: "Drooling" },
                    { value: "weight_loss", label: "Unexplained weight loss" },
                  ],
                },
              ],
            },
          },
          {
            sectionType: "ST_LANGUAGE",
            title: "Language Assessment",
            description: "Expressive and receptive language",
            displayOrder: 5,
            items: {
              create: [
                {
                  code: "ST_EXPRESSIVE",
                  question: "Expressive Language",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mildly_impaired", label: "Mildly Impaired" },
                    { value: "moderately_impaired", label: "Moderately Impaired" },
                    { value: "severely_impaired", label: "Severely Impaired" },
                  ],
                },
                {
                  code: "ST_RECEPTIVE",
                  question: "Receptive Language/Comprehension",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mildly_impaired", label: "Mildly Impaired" },
                    { value: "moderately_impaired", label: "Moderately Impaired" },
                    { value: "severely_impaired", label: "Severely Impaired" },
                  ],
                },
                {
                  code: "ST_NAMING",
                  question: "Naming/Word Finding",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mildly_impaired", label: "Mildly Impaired" },
                    { value: "moderately_impaired", label: "Moderately Impaired" },
                    { value: "severely_impaired", label: "Severely Impaired" },
                  ],
                },
                {
                  code: "ST_READING",
                  question: "Reading Comprehension",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 4,
                  isRequired: false,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mildly_impaired", label: "Mildly Impaired" },
                    { value: "moderately_impaired", label: "Moderately Impaired" },
                    { value: "severely_impaired", label: "Severely Impaired" },
                    { value: "not_tested", label: "Not Tested" },
                  ],
                },
                {
                  code: "ST_WRITING",
                  question: "Writing Ability",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 5,
                  isRequired: false,
                  responseOptions: [
                    { value: "wnl", label: "Within Normal Limits" },
                    { value: "mildly_impaired", label: "Mildly Impaired" },
                    { value: "moderately_impaired", label: "Moderately Impaired" },
                    { value: "severely_impaired", label: "Severely Impaired" },
                    { value: "not_tested", label: "Not Tested" },
                  ],
                },
              ],
            },
          },
          {
            sectionType: "ST_TREATMENT_PLAN",
            title: "Treatment Plan",
            description: "Goals and planned interventions",
            displayOrder: 6,
            items: {
              create: [
                {
                  code: "ST_SHORT_TERM_GOALS",
                  question: "Short-Term Goals (2-4 weeks)",
                  responseType: "TEXT",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "ST_LONG_TERM_GOALS",
                  question: "Long-Term Goals (Discharge)",
                  responseType: "TEXT",
                  displayOrder: 2,
                  isRequired: true,
                },
                {
                  code: "ST_INTERVENTIONS",
                  question: "Planned Interventions",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "cognitive_therapy", label: "Cognitive-Linguistic Therapy" },
                    { value: "speech_therapy", label: "Speech/Articulation Therapy" },
                    { value: "voice_therapy", label: "Voice Therapy" },
                    { value: "dysphagia_therapy", label: "Dysphagia Therapy" },
                    { value: "oral_motor", label: "Oral Motor Exercises" },
                    { value: "compensatory", label: "Compensatory Strategies" },
                    { value: "aac", label: "AAC (Augmentative Communication)" },
                    { value: "caregiver_training", label: "Caregiver Training" },
                  ],
                },
                {
                  code: "ST_FREQUENCY",
                  question: "Recommended Frequency",
                  responseType: "TEXT",
                  displayOrder: 4,
                  isRequired: true,
                },
                {
                  code: "ST_REHAB_POTENTIAL",
                  question: "Rehabilitation Potential",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 5,
                  isRequired: true,
                  responseOptions: [
                    { value: "excellent", label: "Excellent" },
                    { value: "good", label: "Good" },
                    { value: "fair", label: "Fair" },
                    { value: "guarded", label: "Guarded" },
                    { value: "poor", label: "Poor" },
                  ],
                },
              ],
            },
          },
        ],
      },
    },
  });
  console.log(`Created ST Evaluation template: ${stTemplate.id}`);

  // Nursing Assessment Template
  const nursingTemplate = await prisma.assessmentTemplate.create({
    data: {
      name: "Skilled Nursing Assessment",
      description: "Initial nursing assessment for home health patients (v1 - Simplified)",
      version: 1,
      isActive: true,
      isRequired: false,
      displayOrder: 4,
      scoringMethod: "CUSTOM",
      sections: {
        create: [
          {
            sectionType: "NURSING_VITALS",
            title: "Vital Signs",
            description: "Current vital signs",
            displayOrder: 1,
            items: {
              create: [
                {
                  code: "NURSING_BP_SYSTOLIC",
                  question: "Blood Pressure - Systolic",
                  responseType: "NUMBER",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "NURSING_BP_DIASTOLIC",
                  question: "Blood Pressure - Diastolic",
                  responseType: "NUMBER",
                  displayOrder: 2,
                  isRequired: true,
                },
                {
                  code: "NURSING_PULSE",
                  question: "Pulse (beats/min)",
                  responseType: "NUMBER",
                  displayOrder: 3,
                  isRequired: true,
                },
                {
                  code: "NURSING_PULSE_RHYTHM",
                  question: "Pulse Rhythm",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 4,
                  isRequired: true,
                  responseOptions: [
                    { value: "regular", label: "Regular" },
                    { value: "irregular", label: "Irregular" },
                  ],
                },
                {
                  code: "NURSING_RESPIRATIONS",
                  question: "Respirations (breaths/min)",
                  responseType: "NUMBER",
                  displayOrder: 5,
                  isRequired: true,
                },
                {
                  code: "NURSING_TEMP",
                  question: "Temperature (F)",
                  responseType: "NUMBER",
                  displayOrder: 6,
                  isRequired: true,
                },
                {
                  code: "NURSING_O2_SAT",
                  question: "Oxygen Saturation (%)",
                  responseType: "NUMBER",
                  displayOrder: 7,
                  isRequired: false,
                },
                {
                  code: "NURSING_WEIGHT",
                  question: "Weight (lbs)",
                  responseType: "NUMBER",
                  displayOrder: 8,
                  isRequired: false,
                },
              ],
            },
          },
          {
            sectionType: "PAIN",
            title: "Pain Assessment",
            description: "Current pain status",
            displayOrder: 2,
            items: {
              create: [
                {
                  code: "NURSING_PAIN_PRESENT",
                  question: "Is pain present?",
                  responseType: "YES_NO",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "NURSING_PAIN_LEVEL",
                  question: "Pain Level (0-10)",
                  responseType: "SCALE",
                  displayOrder: 2,
                  isRequired: false,
                  minValue: 0,
                  maxValue: 10,
                  showIf: { itemCode: "NURSING_PAIN_PRESENT", value: true },
                },
                {
                  code: "NURSING_PAIN_LOCATION",
                  question: "Pain Location(s)",
                  responseType: "TEXT",
                  displayOrder: 3,
                  isRequired: false,
                  showIf: { itemCode: "NURSING_PAIN_PRESENT", value: true },
                },
                {
                  code: "NURSING_PAIN_MANAGEMENT",
                  question: "Current Pain Management",
                  responseType: "TEXT",
                  displayOrder: 4,
                  isRequired: false,
                  showIf: { itemCode: "NURSING_PAIN_PRESENT", value: true },
                },
              ],
            },
          },
          {
            sectionType: "NURSING_CARDIOPULMONARY",
            title: "Cardiopulmonary Assessment",
            description: "Heart and lung assessment",
            displayOrder: 3,
            items: {
              create: [
                {
                  code: "NURSING_HEART_SOUNDS",
                  question: "Heart Sounds",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "normal", label: "Normal S1/S2" },
                    { value: "murmur", label: "Murmur present" },
                    { value: "irregular", label: "Irregular rhythm" },
                    { value: "s3_s4", label: "S3/S4 present" },
                  ],
                },
                {
                  code: "NURSING_LUNG_SOUNDS",
                  question: "Lung Sounds",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "clear", label: "Clear bilaterally" },
                    { value: "diminished", label: "Diminished" },
                    { value: "crackles", label: "Crackles/Rales" },
                    { value: "wheezes", label: "Wheezes" },
                    { value: "rhonchi", label: "Rhonchi" },
                  ],
                },
                {
                  code: "NURSING_EDEMA",
                  question: "Edema Present",
                  responseType: "YES_NO",
                  displayOrder: 3,
                  isRequired: true,
                },
                {
                  code: "NURSING_EDEMA_LOCATION",
                  question: "Edema Location and Severity",
                  responseType: "TEXT",
                  displayOrder: 4,
                  isRequired: false,
                  showIf: { itemCode: "NURSING_EDEMA", value: true },
                },
                {
                  code: "NURSING_DYSPNEA",
                  question: "Dyspnea",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 5,
                  isRequired: true,
                  responseOptions: [
                    { value: "none", label: "None" },
                    { value: "exertion", label: "With exertion" },
                    { value: "minimal", label: "With minimal exertion" },
                    { value: "rest", label: "At rest" },
                  ],
                },
              ],
            },
          },
          {
            sectionType: "NURSING_NEUROLOGICAL",
            title: "Neurological Assessment",
            description: "Mental and neurological status",
            displayOrder: 4,
            items: {
              create: [
                {
                  code: "NURSING_LOC",
                  question: "Level of Consciousness",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "alert", label: "Alert and oriented" },
                    { value: "confused", label: "Confused" },
                    { value: "lethargic", label: "Lethargic" },
                    { value: "obtunded", label: "Obtunded" },
                    { value: "unresponsive", label: "Unresponsive" },
                  ],
                },
                {
                  code: "NURSING_ORIENTATION",
                  question: "Orientation",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "person", label: "Person" },
                    { value: "place", label: "Place" },
                    { value: "time", label: "Time" },
                    { value: "situation", label: "Situation" },
                  ],
                },
                {
                  code: "NURSING_PUPILS",
                  question: "Pupils",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 3,
                  isRequired: true,
                  responseOptions: [
                    { value: "perrla", label: "PERRLA (normal)" },
                    { value: "sluggish", label: "Sluggish reaction" },
                    { value: "unequal", label: "Unequal" },
                    { value: "fixed", label: "Fixed/Non-reactive" },
                  ],
                },
                {
                  code: "NURSING_MOTOR_STRENGTH",
                  question: "Motor Strength",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 4,
                  isRequired: true,
                  responseOptions: [
                    { value: "normal", label: "Normal/Equal bilateral" },
                    { value: "weakness_left", label: "Left-sided weakness" },
                    { value: "weakness_right", label: "Right-sided weakness" },
                    { value: "weakness_bilateral", label: "Bilateral weakness" },
                  ],
                },
              ],
            },
          },
          {
            sectionType: "NURSING_SKIN",
            title: "Skin Assessment",
            description: "Skin integrity and wound status",
            displayOrder: 5,
            items: {
              create: [
                {
                  code: "NURSING_SKIN_INTEGRITY",
                  question: "Skin Integrity",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 1,
                  isRequired: true,
                  responseOptions: [
                    { value: "intact", label: "Intact" },
                    { value: "impaired", label: "Impaired" },
                  ],
                },
                {
                  code: "NURSING_SKIN_COLOR",
                  question: "Skin Color",
                  responseType: "SINGLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "normal", label: "Normal for ethnicity" },
                    { value: "pale", label: "Pale" },
                    { value: "cyanotic", label: "Cyanotic" },
                    { value: "jaundiced", label: "Jaundiced" },
                    { value: "flushed", label: "Flushed" },
                  ],
                },
                {
                  code: "NURSING_WOUNDS",
                  question: "Wounds Present",
                  responseType: "YES_NO",
                  displayOrder: 3,
                  isRequired: true,
                },
                {
                  code: "NURSING_WOUND_DESCRIPTION",
                  question: "Wound Description",
                  responseType: "TEXT",
                  displayOrder: 4,
                  isRequired: false,
                  description: "Include: Location, size, stage, drainage, treatment",
                  showIf: { itemCode: "NURSING_WOUNDS", value: true },
                },
                {
                  code: "NURSING_BRADEN_SCORE",
                  question: "Braden Scale Score (if applicable)",
                  responseType: "NUMBER",
                  displayOrder: 5,
                  isRequired: false,
                  description: "6-23, lower = higher risk",
                },
              ],
            },
          },
          {
            sectionType: "FALL_RISK",
            title: "Fall Risk Assessment",
            description: "Fall risk factors",
            displayOrder: 6,
            scoringMethod: "SUM",
            items: {
              create: [
                {
                  code: "NURSING_FALL_HISTORY",
                  question: "History of falls (past 6 months)",
                  responseType: "YES_NO",
                  displayOrder: 1,
                  isRequired: true,
                  scoreMapping: { "true": 1, "false": 0 },
                },
                {
                  code: "NURSING_FALL_GAIT",
                  question: "Gait/balance problems",
                  responseType: "YES_NO",
                  displayOrder: 2,
                  isRequired: true,
                  scoreMapping: { "true": 1, "false": 0 },
                },
                {
                  code: "NURSING_FALL_MEDICATIONS",
                  question: "High-risk medications (sedatives, BP meds, etc.)",
                  responseType: "YES_NO",
                  displayOrder: 3,
                  isRequired: true,
                  scoreMapping: { "true": 1, "false": 0 },
                },
                {
                  code: "NURSING_FALL_VISION",
                  question: "Vision impairment",
                  responseType: "YES_NO",
                  displayOrder: 4,
                  isRequired: true,
                  scoreMapping: { "true": 1, "false": 0 },
                },
                {
                  code: "NURSING_FALL_COGNITION",
                  question: "Cognitive impairment",
                  responseType: "YES_NO",
                  displayOrder: 5,
                  isRequired: true,
                  scoreMapping: { "true": 1, "false": 0 },
                },
                {
                  code: "NURSING_FALL_AGE",
                  question: "Age 65 or older",
                  responseType: "YES_NO",
                  displayOrder: 6,
                  isRequired: true,
                  scoreMapping: { "true": 1, "false": 0 },
                },
              ],
            },
          },
          {
            sectionType: "NURSING_TREATMENT_PLAN",
            title: "Care Plan Summary",
            description: "Nursing care priorities and plan",
            displayOrder: 7,
            items: {
              create: [
                {
                  code: "NURSING_PRIORITY_PROBLEMS",
                  question: "Priority Nursing Problems",
                  responseType: "TEXT",
                  displayOrder: 1,
                  isRequired: true,
                },
                {
                  code: "NURSING_INTERVENTIONS",
                  question: "Planned Nursing Interventions",
                  responseType: "MULTIPLE_CHOICE",
                  displayOrder: 2,
                  isRequired: true,
                  responseOptions: [
                    { value: "vital_signs", label: "Vital Signs Monitoring" },
                    { value: "medication_mgmt", label: "Medication Management" },
                    { value: "wound_care", label: "Wound Care" },
                    { value: "disease_mgmt", label: "Disease Management Education" },
                    { value: "pain_mgmt", label: "Pain Management" },
                    { value: "fall_prevention", label: "Fall Prevention" },
                    { value: "nutrition", label: "Nutrition/Hydration" },
                    { value: "catheter_care", label: "Catheter/Ostomy Care" },
                    { value: "iv_therapy", label: "IV Therapy" },
                    { value: "lab_monitoring", label: "Lab Monitoring" },
                  ],
                },
                {
                  code: "NURSING_VISIT_FREQUENCY",
                  question: "Recommended Visit Frequency",
                  responseType: "TEXT",
                  displayOrder: 3,
                  isRequired: true,
                },
                {
                  code: "NURSING_HOMEBOUND",
                  question: "Homebound Status Justification",
                  responseType: "TEXT",
                  displayOrder: 4,
                  isRequired: true,
                },
              ],
            },
          },
        ],
      },
    },
  });
  console.log(`Created Nursing Assessment template: ${nursingTemplate.id}`);

  console.log("\n✅ Assessment templates seeded successfully!");
  console.log(`   - PT Evaluation: ${ptTemplate.id}`);
  console.log(`   - OT Evaluation: ${otTemplate.id}`);
  console.log(`   - ST Evaluation: ${stTemplate.id}`);
  console.log(`   - Nursing Assessment: ${nursingTemplate.id}`);
}

seedAssessmentTemplates()
  .catch((e) => {
    console.error("Error seeding assessment templates:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
