import { z } from "zod";

import { InferSchema } from "@/types";

export const visitSchema = z.object({
  dateFrom: z.date().optional().nullable(),
  dateThrough: z.date().optional().nullable(),
  patient: z.string().optional(),
  allPatient: z.boolean().optional(),
  inActivePatient: z.boolean().optional(),
  caregiver: z.string().optional(),
  allCaregiver: z.boolean().optional(),
  visitStatus: z.string().optional(),
  groupBy: z.string().optional(),
  sortBy: z.string().optional(),
  noCaregiverAssigned: z.boolean().optional(),
  noPatientAssigned: z.boolean().optional(),
  office: z.string().optional(),
  allOffice: z.boolean().optional(),
  billingCode: z.string().optional(),
  allBillingCode: z.boolean().optional(),
  allDiscipline: z.boolean().optional(),
  disciplineType: z.string().optional(),
  discipline: z.string().optional(),
  payer: z.string().optional(),
  allPayer: z.boolean().optional(),
  payrollStatus: z.string().optional(),
  amount: z.string().optional(),
  billedVisit: z.string().optional(),
  billableVisit: z.string().optional(),
  patientRegion: z.string().optional(),
  allPatientRegion: z.boolean().optional(),
});

export type VisitForm = InferSchema<typeof visitSchema>;

export const visitDefaultValue: VisitForm = {
  dateFrom: undefined,
  dateThrough: undefined,
  patient: "",
  allPatient: false,
  inActivePatient: false,
  caregiver: "",
  allCaregiver: false,
  visitStatus: "",
  noCaregiverAssigned: false,
  noPatientAssigned: false,
  office: "",
  allOffice: false,
  billingCode: "",
  allBillingCode: false,
  allDiscipline: false,
  disciplineType: "",
  discipline: "",
  payer: "",
  allPayer: false,
  payrollStatus: "",
  amount: "",
  billedVisit: "",
  billableVisit: "",
  patientRegion: "",
  allPatientRegion: false,
};
