import { Router } from 'express';

import approveForm from './approveform';
import auth from './auth';
import biodata from './biodata';
import cjis from './cjisForm';
import employeeform from './employeeform';
import events from './events';
import fluForm from './fluForm';
import handBook from './handbook';
import hepatitisBForm from './hepatitisBform';
import i9Form from './i9form';
import influenzaForm from './influenzaform';
import intake from './intake';
import mmrForm from './mmrForm';
import n95Form from './n95Form';
import pneumococcalForm from './pneumococcalVaccineForm';
import referenceForm from './referenceform';
import treatment from './treatmentPlan';
import tuberculosisForm from './tuberculosisMantouxForm';
import upload from './upload';
import users from './users';
import varicellaForm from './varicellaForm';
import visit from './visit';
import fcVisit from './fcVisit';
import specificNeed from './specificNeed';
import sixMonthReport from './sixMonthReport';
import dashboard from './dashboard';
import clientStaffAssignment from './clientStaffAssignment';

const router = Router();

router.use('/auth', auth);
router.use('/users', users);
router.use('/biodata', biodata);
router.use('/i9form', i9Form);
router.use('/upload', upload);
router.use('/employeeform', employeeform);
router.use('/pneumococcalForm', pneumococcalForm);
router.use('/tuberculosisForm', tuberculosisForm);
router.use('/hepatitisBForm', hepatitisBForm);
router.use('/varicellaForm', varicellaForm);
router.use('/mmrForm', mmrForm);
router.use('/fluForm', fluForm);
router.use('/influenzaForm', influenzaForm);
router.use('/n95Form', n95Form);
router.use('/approveform', approveForm);
router.use('/intake', intake);
router.use('/referenceForm', referenceForm);
router.use('/handbook', handBook);
router.use('/cjis', cjis);
router.use('/treatment', treatment);
router.use('/visit', visit);
router.use('/events', events);
router.use('/fcVisit', fcVisit);
router.use('/specificNeed', specificNeed);
router.use('/six-month-report', sixMonthReport);
router.use('/dashboard', dashboard);
router.use('/client-staff-assignment', clientStaffAssignment);

export default router;
