import { z } from "zod";

import { InferSchema } from "@/types";

export const oasisFollowUpSchema = z.object({
  serviceProvided: z.string().optional(),
  qCode: z.string().optional(),
  serviceVisit: z.string().optional(),
  certificationNumber: z.string().optional(),
  branchState: z.string().optional(),
  branchId: z.string().optional(),
  attendingPhysician: z.string().optional(),
  physicianNpi: z.string().optional(),
  patientId: z.string().optional(),
  startOfCare: z.date().optional(),
  resumptionOfCare: z.date().optional(),
  firstName: z.string().optional(),
  patientMi: z.string().optional(),
  lastName: z.string().optional(),
  suffix: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zip: z.string().optional(),
  medicareNumber: z.string().optional(),
  ssn: z.string().optional(),
  medicaidNumber: z.string().optional(),
  dob: z.date().optional(),
  gender: z.string().optional(),
  paymentSource: z.array(z.string()).optional(),
  otherPaymentSource: z.string().optional(),
  serviceDiscipline: z.string().optional(),
  visitDate: z.date().optional(),
  dateAssessmentCompleted: z.date().optional(),
  timeIn: z.string().optional(),
  timeOut: z.string().optional(),
  assessmentReason: z.array(z.string()).optional(),
  episodeTiming: z.string().optional(),
  admissionSource: z.string().optional(),
  signatureCompleting: z.string().optional(),
  signatureCompletingDate: z.date().optional(),
  signatureRevising: z.string().optional(),
  signatureRevisingDate: z.date().optional(),
  milesTravelled: z.string().optional(),
  electronicInitials: z.string().optional(),
});

export type OasisFollowUpForm = InferSchema<typeof oasisFollowUpSchema>;

export const oasisFollowUpDefaultValue: OasisFollowUpForm = {
  serviceProvided: "",
  qCode: "",
  serviceVisit: "",
  certificationNumber: "",
  branchState: "",
  branchId: "",
  attendingPhysician: "",
  physicianNpi: "",
  patientId: "",
  startOfCare: undefined,
  resumptionOfCare: undefined,
  firstName: "",
  patientMi: "",
  lastName: "",
  suffix: "",
  address: "",
  city: "",
  state: "",
  zip: "",
  medicareNumber: "",
  ssn: "",
  medicaidNumber: "",
  dob: undefined,
  gender: "",
  paymentSource: [],
  otherPaymentSource: "",
  serviceDiscipline: "",
  visitDate: undefined,
  dateAssessmentCompleted: undefined,
  timeIn: "",
  timeOut: "",
  assessmentReason: [],
  episodeTiming: "",
  admissionSource: "",
  signatureCompleting: "",
  signatureCompletingDate: undefined,
  signatureRevising: "",
  signatureRevisingDate: undefined,
  milesTravelled: "",
  electronicInitials: "",
};
