import { z } from "zod";

import { InferSchema } from "@/types";

import { physicianDefaultValue, PhysicianSchema } from "./admission";

export const patientFormSchema = z
  .object({
    firstName: z.string().optional(),
    middleInitial: z.string().optional(),
    lastName: z.string().optional(),
    dob: z.date().optional().nullable(),
    ssn: z.string().optional(),
    patientNo: z.string().optional(),
    phone: z.string().optional(),
    medicaidNumber: z.string().optional(),
    medicareNumber: z.string().optional(),
    notMedicareNumber: z.boolean().optional(),
    address1: z.string().optional(),
    address2: z.string().optional(),
    city: z.string().optional(),
    country: z.string().optional(),
    state: z.string().optional(),
    zip: z.string().optional(),
    gender: z.string().optional(),
    maritalStatus: z.string().optional(),
    workersComp: z.string().optional(),
    race: z.string().optional(),
    referralSource: z.string().optional(),
    physician: PhysicianSchema.optional(),
    dme: z.string().optional(),
    dmeSupplies: z.string().optional(),
    suffix: z.string().optional(),
    controlNumber: z.string().optional(),
    admissionSOC: z.date().optional().nullable(),
    CBSACode: z.string().optional(),
    admissionSource: z.string().optional(),
    admissionPriority: z.string().optional(),
    authorizationNumber: z.string().optional(),
    employmentStatus: z.string().optional(),
    faceToFace: z.date().optional().nullable(),
    taxonomy: z.string().optional(),
    taxonomyCode: z.string().optional(),
    conditionRelation: z.array(z.string()).optional(),
    sharePatient: z.boolean().optional(),
    supervisingPhysician: z.string().optional().nullable(),
    supervisingPhysicianNpi: z.string().optional().nullable(),
    student: z.string().optional(),
    county: z.string().optional(),
    notAPhysician: z.boolean().optional(),
    autoAccidentState: z.string().optional().nullable(),
  })
  .refine((args) => (args.ssn ? args.ssn.length === 4 : true), {
    message: "SSN should be 4 digits",
    path: ["ssn"],
  });

export type PatientForm = InferSchema<typeof patientFormSchema>;

export const patientDefaultValue: PatientForm = {
  firstName: "",
  middleInitial: "",
  lastName: "",
  dob: undefined,
  ssn: "",
  phone: "",
  patientNo: "",
  medicaidNumber: "",
  medicareNumber: "",
  address1: "",
  address2: "",
  city: "",
  state: "",
  country: "",
  zip: "",
  gender: "",
  maritalStatus: "",
  workersComp: "",
  race: "",
  referralSource: "",
  dme: "",
  dmeSupplies: "",
  suffix: "",
  controlNumber: "",
  admissionSOC: undefined,
  CBSACode: "",
  admissionSource: "",
  admissionPriority: "",
  authorizationNumber: "",
  employmentStatus: "",
  faceToFace: undefined,
  taxonomy: "",
  taxonomyCode: "",
  conditionRelation: [],
  sharePatient: false,
  supervisingPhysician: "",
  supervisingPhysicianNpi: "",
  notMedicareNumber: false,
  notAPhysician: false,
  physician: physicianDefaultValue,
  autoAccidentState: "",
};
