import z from "zod";

import { InferSchema } from "@/types";

export const parentHistorySchema = z
  .object({
    address: z.string().optional().nullable(),
    advanceDirectives: z.array(z.string()).optional().nullable(),
    advanceDirectivesOther: z.boolean(),
    advanceDirectivesOtherComment: z.string().optional().nullable(),
    advanceDirectivesTeaching: z.string().optional().nullable(),
    allergies: z.array(z.string()).optional().nullable(),
    anemia: z.boolean(),
    anemiaComment: z.string().optional().nullable(),
    bloodSugar: z.boolean(),
    bloodSugarComment: z.string().optional().nullable(),
    bloodSugarPerformer: z.array(z.string()).optional().nullable(),
    bloodSugarRange: z.string().optional().nullable(),
    cancerSites: z.boolean(),
    cancerComment: z.string().optional().nullable(),
    dateLastContacted: z.date().optional().nullable(),
    dateLastVisited: z.date().optional().nullable(),
    dateOfVisit: z.date(),
    deaf: z.array(z.string()).optional().nullable(),
    diabetes: z.string().optional().nullable(),
    dietControl: z.string().optional().nullable(),
    dob: z.date().optional().nullable(),
    earProblem: z.array(z.string()).optional().nullable(),
    noEarProblem: z.boolean(),
    enlargedThyriod: z.array(z.string()).optional().nullable(),
    eyeProblemVision: z.array(z.string()).optional().nullable(),
    eyesCataract: z.boolean(),
    eyesCataractComment: z.string().optional().nullable(),
    eyesCataractDate: z.date().optional().nullable(),
    eyesContact: z.array(z.string()).optional().nullable(),
    eyesInfection: z.boolean(),
    eyesInfectionComment: z.string().optional().nullable(),
    eyesProblem: z.array(z.string()).optional().nullable(),
    firstName: z.string().optional().nullable(),
    gender: z.string().optional().nullable(),
    headNeckProblem: z.array(z.string()).optional().nullable(),
    healthInsuranceName: z.string().optional().nullable(),
    hearingAid: z.array(z.string()).optional().nullable(),
    hoh: z.array(z.string()).optional().nullable(),
    hyperglycemia: z.array(z.string()).optional().nullable(),
    hypoglycemia: z.array(z.string()).optional().nullable(),
    immunizations: z.boolean(),
    insulinDose: z.string().optional().nullable(),
    lastName: z.string().optional().nullable(),
    livingArrangement: z.array(z.string()).optional().nullable(),
    livingArrangementADL: z.array(z.string()).optional().nullable(),
    livingArrangementOther: z.boolean(),
    mouthDentures: z.boolean(),
    mouthProblem: z.array(z.string()).optional().nullable(),
    mouthProblemPart: z.array(z.string()).optional().nullable(),
    needs: z.array(z.string()).optional().nullable(),
    needsSpecify: z.string().optional().nullable(),
    newDiagnosis: z.string().optional().nullable(),
    noAllergiesProblem: z.boolean(),
    noEyeProblem: z.boolean(),
    noEndocrineProblem: z.boolean(),
    noThroatProblem: z.boolean(),
    noHeadNeckProblem: z.boolean(),
    noMouthProblem: z.boolean(),
    noNoseProblem: z.boolean(),
    noOfTimes: z.string().optional().nullable(),
    noseProblem: z.array(z.string()).optional().nullable(),
    otherAllergies: z.boolean(),
    otherAllergiesComment: z.string().optional().nullable(),
    otherCaregiver: z.boolean(),
    otherCaregiverComment: z.string().optional().nullable(),
    otherComment: z.string().optional().nullable(),
    otherThroatProblem: z.boolean(),
    otherThroatProblemComment: z.string().optional().nullable(),
    otherEarsHistory: z.boolean(),
    otherEarsHistoryComment: z.string().optional().nullable(),
    otherEyesHistory: z.boolean(),
    otherEyesHistoryComment: z.string().optional().nullable(),
    otherHeadNeckMasses: z.boolean(),
    otherHeadNeckProblem: z.boolean(),
    otherHeadNeckProblemSite: z.string().optional().nullable(),
    alopecia: z.string().optional().nullable(),
    otherHeadNeckProblemComment: z.string().optional().nullable(),
    otherHeadNeckProblemSize: z.string().optional().nullable(),
    otherMouthProblem: z.boolean(),
    otherMouthProblemComment: z.string().optional().nullable(),
    otherNoseProblem: z.boolean(),
    otherNoseProblemComment: z.string().optional().nullable(),
    otherSecondaryBleed: z.boolean(),
    otherSecondaryBleedComment: z.string().optional().nullable(),
    otherenlargedThyriodProblem: z.boolean(),
    otherenlargedThyriodProblemComment: z.string().optional().nullable(),
    patientHistory: z.array(z.string()).optional().nullable(),
    patientReport: z.boolean(),
    phoneNo: z.string().optional().nullable(),
    presentIllness: z.string().optional().nullable(),
    primaryCaregiver: z.string().optional().nullable(),
    primaryReason: z.string().optional().nullable(),
    priorHospitalization: z.string().optional().nullable(),
    priorHospitalizationDate: z.date().optional().nullable(),
    priorHospitalizationReason: z.string().optional().nullable(),
    prognosis: z.string().optional().nullable(),
    recentHospitalization: z.string().optional().nullable(),
    recentHospitalizationDate: z.date().optional().nullable(),
    recentHospitalizationReason: z.string().optional().nullable(),
    relationship: z.string().optional().nullable(),
    secondaryBleed: z.array(z.string()).optional().nullable(),
    socDate: z.date().optional().nullable(),
    specify: z.string().optional().nullable(),
    state: z.string().optional().nullable(),
    surgeries: z.boolean(),
    surgeriesComment: z.string().optional().nullable(),
    timeIn: z.string(),
    timeOut: z.string(),
    zipCode: z.string().optional().nullable(),
    cancerInfection: z.array(z.string()).optional().nullable(),
    throatProblem: z.array(z.string()).optional().nullable(),
  })
  .refine(
    (data) => {
      if (data.timeIn && data.timeOut) {
        const timeIn = new Date(`01/01/2024 ${data.timeIn}`);
        const timeOut = new Date(`01/01/2024 ${data.timeOut}`);
        return timeIn < timeOut;
      } else return true;
    },
    {
      message: "Time In must be less than Time Out",
      path: ["timeOut"],
    },
  );

export type PatientHistoryForm = InferSchema<typeof parentHistorySchema>;

export const patientHistoryDefaultValue: PatientHistoryForm = {
  address: "",
  advanceDirectives: [],
  advanceDirectivesOtherComment: "",
  advanceDirectivesTeaching: "",
  allergies: [],
  anemiaComment: "",
  bloodSugarComment: "",
  bloodSugarPerformer: [],
  bloodSugarRange: "",
  cancerComment: "",
  cancerInfection: [],
  dateLastContacted: null,
  dateLastVisited: null,
  dateOfVisit: new Date(),
  deaf: [],
  diabetes: "",
  dietControl: "",
  dob: null,
  earProblem: [],
  enlargedThyriod: [],
  eyeProblemVision: [],
  eyesCataractComment: "",
  eyesCataractDate: null,
  eyesContact: [],
  eyesInfectionComment: "",
  eyesProblem: [],
  firstName: "",
  gender: "",
  headNeckProblem: [],
  healthInsuranceName: "",
  hearingAid: [],
  hoh: [],
  hyperglycemia: [],
  hypoglycemia: [],
  insulinDose: "",
  lastName: "",
  livingArrangement: [],
  livingArrangementADL: [],
  mouthProblem: [],
  mouthProblemPart: [],
  needs: [],
  needsSpecify: "",
  newDiagnosis: "",
  noOfTimes: "",
  noseProblem: [],
  otherAllergiesComment: "",
  otherCaregiverComment: "",
  otherComment: "",
  otherThroatProblemComment: "",
  otherEarsHistoryComment: "",
  otherEyesHistoryComment: "",
  otherHeadNeckProblem: false,
  otherHeadNeckProblemComment: "",
  otherHeadNeckProblemSize: "",
  otherMouthProblemComment: "",
  otherNoseProblemComment: "",
  otherSecondaryBleedComment: "",
  otherenlargedThyriodProblemComment: "",
  patientHistory: [],
  phoneNo: "",
  presentIllness: "",
  primaryCaregiver: "",
  primaryReason: "",
  priorHospitalization: "",
  priorHospitalizationDate: null,
  priorHospitalizationReason: "",
  prognosis: "",
  recentHospitalization: "",
  recentHospitalizationDate: null,
  recentHospitalizationReason: "",
  relationship: "",
  secondaryBleed: [],
  socDate: null,
  specify: "",
  state: "",
  surgeriesComment: "",
  timeIn: "",
  zipCode: "",
  alopecia: "",
  advanceDirectivesOther: false,
  anemia: false,
  bloodSugar: false,
  cancerSites: false,
  noEarProblem: false,
  eyesCataract: false,
  eyesInfection: false,
  immunizations: false,
  livingArrangementOther: false,
  mouthDentures: false,
  noAllergiesProblem: false,
  noEyeProblem: false,
  noEndocrineProblem: false,
  noThroatProblem: false,
  noHeadNeckProblem: false,
  noMouthProblem: false,
  noNoseProblem: false,
  otherAllergies: false,
  otherCaregiver: false,
  otherThroatProblem: false,
  otherEarsHistory: false,
  otherEyesHistory: false,
  otherHeadNeckMasses: false,
  otherMouthProblem: false,
  otherNoseProblem: false,
  otherSecondaryBleed: false,
  otherenlargedThyriodProblem: false,
  patientReport: false,
  surgeries: false,
  timeOut: "",
  throatProblem: [],
};
