import { z } from "zod";

import { InferSchema } from "@/types";

export const medicationFormSchema = z.object({
  id: z.string().optional(),
  medication: z.array(
    z.object({
      id: z.string().optional(),
      date: z.date().optional().nullable(),
      drug: z.string().optional().nullable(),
      dose: z.string().optional().nullable(),
      frequency: z.string().optional().nullable(),
      route: z.string().optional().nullable(),
      NorC: z.string().optional().nullable(),
      sideEffect: z.string().optional().nullable(),
      medClassification: z.string().optional().nullable(),
      dcDate: z.date().optional().nullable(),
      signature: z.string().optional().nullable(),
    }),
  ),
  primaryDx: z.object({
    id: z.string().optional(),
    name: z.string().optional().nullable(),
    dateType: z.string().optional().nullable(),
    date: z.date().optional().nullable(),
  }),
  otherDx: z.array(
    z.object({
      id: z.string().optional(),
      name: z.string().optional().nullable(),
      dateType: z.string().optional().nullable(),
      date: z.date().optional().nullable(),
    }),
  ),
  MIO12InpatientProcedure: z.array(
    z.object({
      id: z.string().optional(),
      name: z.string().optional().nullable(),
      dateType: z.string().optional().nullable(),
      date: z.date().optional().nullable(),
    }),
  ),
  ulcerComments: z.string().optional().nullable(),
  pressureUlcer: z.string().optional().nullable(),
  functionLimits: z.array(z.string()).optional().nullable(),
  rue: z.string().optional().nullable(),
  activitiesAndDiet: z.array(z.string()).optional().nullable(),
  wtBearing: z.string().optional().nullable(),
  assistiveDevice: z.string().optional().nullable(),
  diet: z.string().optional().nullable(),
  allergies: z.string().optional().nullable(),
  M1045InfluenzaVaccine: z.date().optional().nullable(),
  M1045InfluenzaVaccineReceived: z.string().optional().nullable(),
  M1055PneumococcalVaccine: z.date().optional().nullable(),
  M1055PneumococcalVaccineReceived: z.string().optional().nullable(),
  tetanusVaccine: z.date().optional().nullable(),
  tetanusVaccineReceived: z.string().optional().nullable(),
  otherVaccine: z.date().optional().nullable(),
  otherVaccineReceived: z.string().optional().nullable(),
  foleyCatheter: z.string().optional().nullable(),
  foleyCatheterSize: z.string().optional().nullable(),
  foleyCatheterFrequency: z.string().optional().nullable(),
  foleyCatheterLabWork: z.string().optional().nullable(),
  foleyCatheterDate: z.date().optional().nullable(),
  serviceRequested: z.array(
    z.object({
      id: z.string().optional(),
      service: z.string().optional().nullable(),
      discipline: z.string().optional().nullable(),
      frequency: z.string().optional().nullable(),
    }),
  ),
  serviceRequestedComments: z.string().optional().nullable(),
  serviceRequestedMedication: z.string().optional().nullable(),
  auxiliaryService: z.string().optional().nullable(),
  primaryCaregiver: z.string().optional().nullable(),
  physicianOrders: z.string().optional().nullable(),
  emergencyContact: z.string().optional().nullable(),
  contactNumber: z.string().optional().nullable(),
  medicareAEffective: z.string().optional().nullable(),
  medicareBEffective: z.string().optional().nullable(),
  medicareAEffectiveDate: z.date().optional().nullable(),
  medicareBEffectiveDate: z.date().optional().nullable(),
  initalIntakeNurse: z.string().optional().nullable(),
  initialReferral: z.string().optional().nullable(),
  initialReferralTime: z.string().optional().nullable(),
  finalIntakeNurse: z.string().optional().nullable(),
  finalReferral: z.string().optional().nullable(),
  finalReferralTime: z.string().optional().nullable(),
  nurseComments: z.string().optional().nullable(),
  proposedAdmission: z.string().optional().nullable(),
  proposedAdmissionTime: z.string().optional().nullable(),
  admissionsourceCodeC: z.string().optional().nullable(),
  admissionSourceCodeB: z.string().optional().nullable(),
});

export const medicationDefaultValue = {
  medication: [
    {
      date: undefined,
      drug: "",
      dose: "",
      frequency: "",
      route: "",
      NorC: "",
      sideEffect: "",
      medClassification: "",
      dcDate: undefined,
      signature: "",
    },
  ],
  primaryDx: {
    name: "",
    dateType: "",
    date: undefined,
  },
  otherDx: [
    {
      name: "",
      dateType: "",
      date: undefined,
    },
  ],
  MIO12InpatientProcedure: [
    {
      name: "",
      dateType: "",
      date: undefined,
    },
  ],
  ulcerComments: "",
  pressureUlcer: "",
  functionLimits: [],
  rue: "",
  activitiesAndDiet: [],
  wtBearing: "",
  assistiveDevice: "",
  diet: "",
  allergies: "",
  M1045InfluenzaVaccine: undefined,
  M1045InfluenzaVaccineReceived: "",
  M1055PneumococcalVaccine: undefined,
  M1055PneumococcalVaccineReceived: "",
  tetanusVaccine: undefined,
  tetanusVaccineReceived: "",
  otherVaccine: undefined,
  otherVaccineReceived: "",
  foleyCatheter: "",
  foleyCatheterSize: "",
  foleyCatheterFrequency: "",
  foleyCatheterLabWork: "",
  foleyCatheterDate: undefined,
  serviceRequested: [
    {
      service: "",
      discipline: "",
      frequency: "",
    },
  ],
  serviceRequestedComments: "",
  serviceRequestedMedication: "",
  primaryCaregiver: "",
  physicianOrders: "",
  emergencyContact: "",
  contactNumber: "",
  medicareAEffective: "",
  medicareBEffective: "",
  medicareAEffectiveDate: undefined,
  medicareBEffectiveDate: undefined,
  initalIntakeNurse: "",
  initialReferral: "",
  initialReferralTime: "",
  finalIntakeNurse: "",
  finalReferral: "",
  finalReferralTime: "",
  nurseComments: "",
  proposedAdmission: "",
  proposedAdmissionTime: "",
  admissionsourceCodeC: "",
  admissionSourceCodeB: "",
  auxiliaryService: "",
};

export type PatientMedicationForm = InferSchema<typeof medicationFormSchema>;
