import { z } from "zod";

export const patientTrackingSchema = z.object({
  certificationNUmber: z.string().optional(),
  branchId: z.string().optional(),
  branchState: z.string().optional(),
  npi: z.string().optional(),
  patientNumber: z.string().optional(),
  startDate: z.date().optional(),
  resumptionDate: z.date().optional(),
  changeAdmissionInfo: z.boolean().optional(),
  firstName: z.string().optional(),
  mi: z.string().optional(),
  suffix: z.string().optional(),
  state: z.string().optional(),
  zip: z.string().optional(),
  medicareNumber: z.string().optional(),
  ssn: z.string().optional(),
  medicaidNumber: z.string().optional(),
  birthDate: z.date().optional(),
  gender: z.string().optional(),
  noMedicare: z.boolean().optional(),
  unknown: z.boolean().optional(),
  noMedicaid: z.boolean().optional(),
  dateCompleted: z.date().optional(),
  reasons: z.array(z.string()).nonempty({
    message: "One or more reasons are required",
  }),
  nurseId: z.string().optional(),
});

export type PatientTrackingForm = z.infer<typeof patientTrackingSchema>;

export const patientTrackingDefaultValues = {
  certificationNUmber: "",
  branchId: "",
  branchState: "",
  npi: "",
  patientNumber: "",
  startDate: undefined,
  resumptionDate: undefined,
  changeAdmissionInfo: false,
  firstName: "",
  mi: "",
  suffix: "",
  state: "",
  zip: "",
  medicareNumber: "",
  ssn: "",
  medicaidNumber: "",
  birthDate: undefined,
  gender: "",
  noMedicare: false,
  unknown: false,
  noMedicaid: false,
  dateCompleted: undefined,
  reasons: [],
  nurseId: "",
};
