import { z } from "zod";

import { InferSchema } from "@/types";

export const sectionASchema = z
  .object({
    serviceProvided: z.string().optional(),
    qCode: z.string().optional(),
    serviceVisit: z.string().optional(),
    certificationNumber: z.string().optional(),
    branchState: z.string().optional(),
    branchId: z.string().optional(),
    attendingPhysician: z.string().optional(),
    physicianNpi: z.string().optional(),
    patientId: z.string().optional(),
    startOfCare: z.date().optional(),
    resumptionOfCare: z.date().optional(),
    firstName: z.string().optional(),
    patientMi: z.string().optional(),
    lastName: z.string().optional(),
    suffix: z.string().optional(),
    address: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    zip: z.string().optional(),
    medicareNumber: z.string().optional(),
    ssn: z.string().optional(),
    medicaidNumber: z.string().optional(),
    dob: z.date().optional(),
    gender: z.string().optional(),
    maritalStatus: z.string().optional(),
    ethnicity: z.array(z.string()).optional(),
    race: z.array(z.string()).optional(),
    preferredLanguage: z.string().optional(),
    clinicalRecordItem: z.string().optional(),
    transportation: z.array(z.string()).optional(),
    currentPaymentSource: z.array(z.string()).optional(),
    otherCurrentPaymentSource: z.string().optional(),
    interpreter: z.string().optional(),
    visitDate: z.date().optional(),
    dateCompleted: z.date().optional(),
    timeIn: z.string().optional(),
    timeOut: z.string().optional(),
    isAssessmentPerformedMoreThanOne: z.boolean().optional(),
    socAssessment: z.array(z.string()).optional(),
    isNoSpecificSocDate: z.boolean().optional(),
    socDateOfReferral: z.date().optional(),
    signatureCompleting: z.string().optional(),
    signatureCompletingDate: z.date().optional(),
    signatureRivising: z.string().optional(),
    signatureRivisingDate: z.date().optional(),
    milesTravelled: z.string().optional(),
    electronicInitials: z.string().optional(),
    episodeTiming: z.string().optional(),
    patientAdmissionSource: z.string().optional(),
    inpatientFacilities: z.array(z.string()).optional(),
    otherInpatientFacilities: z.string().optional(),
    inpatientDischargeDate: z.date().optional(),
    isUnknown: z.boolean().optional(),
  })
  .refine(
    (data) => {
      if (data.timeIn && data.timeOut) {
        const timeIn = new Date(`01/01/2024 ${data.timeIn}`);
        const timeOut = new Date(`01/01/2024 ${data.timeOut}`);
        return timeIn < timeOut;
      } else return true;
    },
    {
      message: "Arrival time must be less than departure time",
      path: ["timeOut"],
    },
  );

export type SectionAForm = InferSchema<typeof sectionASchema>;

export const sectionADefaultValue: SectionAForm = {
  serviceProvided: "",
  qCode: "",
  serviceVisit: "",
  certificationNumber: "",
  branchState: "",
  branchId: "",
  attendingPhysician: "",
  physicianNpi: "",
  patientId: "",
  startOfCare: undefined,
  resumptionOfCare: undefined,
  firstName: "",
  patientMi: "",
  lastName: "",
  suffix: "",
  address: "",
  city: "",
  state: "",
  zip: "",
  medicareNumber: "",
  ssn: "",
  medicaidNumber: "",
  dob: undefined,
  gender: "",
  maritalStatus: "",
  ethnicity: [],
  race: [],
  preferredLanguage: "",
  interpreter: "",
  transportation: [],
  currentPaymentSource: [],
  otherCurrentPaymentSource: "",
  clinicalRecordItem: "",
  visitDate: undefined,
  dateCompleted: undefined,
  timeIn: "",
  timeOut: "",
  isAssessmentPerformedMoreThanOne: false,
  socAssessment: [],
  isNoSpecificSocDate: false,
  socDateOfReferral: undefined,
  signatureCompleting: "",
  signatureCompletingDate: undefined,
  signatureRivising: "",
  signatureRivisingDate: undefined,
  milesTravelled: "",
  electronicInitials: "",
  episodeTiming: "",
  patientAdmissionSource: "",
  inpatientFacilities: [],
  otherInpatientFacilities: "",
  inpatientDischargeDate: undefined,
  isUnknown: false,
};
