import z from "zod";

import { InferSchema } from "@/types";

export const AuthorizationSchema = z.object({
  authorizationTracker: z.array(
    z.object({
      startDate: z.date().optional().nullable(),
      endDate: z.date().optional().nullable(),
      status: z.string().optional().nullable(),
      insurance: z.string().optional().nullable(),
      number: z.string().optional().nullable(),
      visitsAuthorized: z.string().optional().nullable(),
      sn: z.string().optional().nullable(),
      pt: z.string().optional().nullable(),
      ot: z.string().optional().nullable(),
      st: z.string().optional().nullable(),
      msw: z.string().optional().nullable(),
      rn: z.string().optional().nullable(),
      lvn: z.string().optional().nullable(),
      caregiver: z.string().optional().nullable(),
      hha: z.string().optional().nullable(),
      rm: z.string().optional().nullable(),
      assLiv: z.string().optional().nullable(),
      empAs: z.string().optional().nullable(),
      peer: z.string().optional().nullable(),
      counselling: z.string().optional().nullable(),
      sud: z.string().optional().nullable(),
      sudg: z.string().optional().nullable(),
      nurse: z.string().optional().nullable(),
      psychRe: z.string().optional().nullable(),
      psychRehg: z.string().optional().nullable(),
      transp: z.string().optional().nullable(),
      supEmp: z.string().optional().nullable(),
      shl: z.string().optional().nullable(),
      hhc: z.string().optional().nullable(),
      sls: z.string().optional().nullable(),
      comment: z.string().optional().nullable(),
    }),
  ),
});
export type AuthorizationForm = InferSchema<typeof AuthorizationSchema>;

export const AuthorizationDefaultValue: AuthorizationForm = {
  authorizationTracker: [
    {
      startDate: undefined,
      endDate: undefined,
      status: "",
      insurance: "",
      number: "",
      visitsAuthorized: "",
      sn: "",
      pt: "",
      ot: "",
      st: "",
      msw: "",
      rn: "",
      lvn: "",
      psychRehg: "",
      caregiver: "",
      hha: "",
      rm: "",
      assLiv: "",
      empAs: "",
      peer: "",
      counselling: "",
      sud: "",
      sudg: "",
      nurse: "",
      psychRe: "",
      comment: "",
    },
  ],
};
