import z from "zod";

import { InferSchema } from "@/types";

export const observationTwoSchema = z.object({
  tugScore: z.string().optional(),
  fallRisksAssessment: z.array(z.string()).optional(),
  isStandTest: z.boolean().optional(),
  standTestNumber: z.string().optional(),
  standTestScore: z.string().optional(),
  isBalancedTest: z.boolean().optional(),
  standWithFeet: z.string().optional(),
  placeInstep: z.string().optional(),
  tandemStand: z.string().optional(),
  standOnOneFoot: z.string().optional(),
  chairRise: z.string().optional(),
  notes: z.string().optional(),
  reasonNotDone: z.string().optional(),
  otherReason: z.string().optional(),
  heart: z.array(z.string()).optional(),
  circulatoryEdema: z.array(z.string()).optional(),
  circulatoryPeripheral: z.array(z.string()).optional(),
  capillaryRefill: z.array(z.string()).optional(),
  pulses: z.string().optional(),
  otherCirculatory: z.string().optional(),
  otherPeripheral: z.string().optional(),
  otherCapillaryRefill: z.string().optional(),
  painRelief: z.string().optional(),
  prescription: z.string().optional(),
  location: z.string().optional(),
  duration: z.string().optional(),
  medication: z.string().optional(),
  frequency: z.string().optional(),
  descriptionOfPain: z.string().optional(),
  painManagementIntervention: z.string().optional(),
  painLevelBeforeMedication: z.string().optional(),
  painLevelAfterMedication: z.string().optional(),
  currentPainLevel: z.string().optional(),
  homeboundStatus: z.array(z.string()).optional(),
  oasisPopulateHomebound: z.string().optional(),
  criteriaOneA: z.string().optional(),
  criteriaOneB: z.string().optional(),
  criteriaTwoA: z.string().optional(),
  criteriaTwoB: z.string().optional(),
  medicalCare: z.string().optional(),
  hospitalRiskAssessment: z.string().optional(),
  standardPrecaution: z.array(z.string()).optional(),
  otherStandardPrecaution: z.string().optional(),
  medicationCompliance: z.string().optional(),
  medicationChange: z.string().optional(),
  woundInfusion: z.array(z.string()).optional(),
});

export type ObservationTwoForm = InferSchema<typeof observationTwoSchema>;

export const observationTwoDefaultValue: ObservationTwoForm = {
  tugScore: "",
  fallRisksAssessment: [],
  isStandTest: false,
  standTestNumber: "",
  standTestScore: "",
  isBalancedTest: false,
  standWithFeet: "",
  placeInstep: "",
  tandemStand: "",
  standOnOneFoot: "",
  chairRise: "",
  notes: "",
  reasonNotDone: "",
  otherReason: "",
  heart: [],
  circulatoryEdema: [],
  circulatoryPeripheral: [],
  capillaryRefill: [],
  pulses: "",
  otherCirculatory: "",
  otherPeripheral: "",
  otherCapillaryRefill: "",
  painRelief: "",
  prescription: "",
  location: "",
  duration: "",
  medication: "",
  frequency: "",
  descriptionOfPain: "",
  painManagementIntervention: "",
  painLevelBeforeMedication: "",
  painLevelAfterMedication: "",
  currentPainLevel: "",
  homeboundStatus: [],
  oasisPopulateHomebound: "",
  criteriaOneA: "",
  criteriaOneB: "",
  criteriaTwoA: "",
  criteriaTwoB: "",
  medicalCare: "",
  hospitalRiskAssessment: "",
  standardPrecaution: [],
  otherStandardPrecaution: "",
  medicationCompliance: "",
  medicationChange: "",
  woundInfusion: [],
};
